import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.scss";
import propagate from "util/math";

const Home: NextPage = () => {
  const [equation, setEquation] = useState("");
  const [result, setResult] = useState("");

  useEffect(() => {
    window.MathJax.typeset();
  }, [result]);

  return (
    <div className={styles["container"]}>
      <Head>
        <title>Uncertainty Propagation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          id="MathJax-script"
          async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        ></script>
      </Head>

      <main className={styles["main"]}>
        <h1>Uncertainty Propagation</h1>
        <p>
          A very basic, yet incredibly useful uncertainty propagation
          calculator.
        </p>
        <input
          type="text"
          value={equation}
          onChange={(e) => setEquation(e.target.value)}
        />

        <button onClick={() => setResult("$$" + propagate(equation) + "$$")}>
          Propagate!
        </button>
        <button
          onClick={() => {
            window.MathJax.typeset();
          }}
        >
          Typeset!
        </button>
        <h2>Result</h2>
        <p>{result}</p>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
