import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.scss";
import propagate from "util/math";
import copy from "copy-to-clipboard";
const globalAny: any = global;

const Home: NextPage = () => {
  const [equation, setEquation] = useState("");
  const [result, setResult] = useState("");
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    setEquation(global.localStorage.getItem("equation") || "");
    (global as any).window.MathJax.typeset();
    setCopied(false);
  }, [result]);

  return (
    <div className={styles["container"]}>
      <Head>
        <title>Uncertainty Propagation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          id="MathJax-script"
          async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        ></script>
      </Head>

      <main className={styles["main"]}>
        <h1>Uncertainty Propagation</h1>
        <p>
          Quite possibly the <i>only</i> uncertainty calculator that outputs the
          relevant LaTeX! The author makes no guarantees regarding the accuracy
          of the results, so use at your own risk.
        </p>
        <input
          type="text"
          placeholder="Type your equation here"
          value={equation}
          onChange={(e) => {
            setEquation(e.target.value);
            localStorage.setItem("equation", e.target.value);
          }}
        />
        <div className={styles["group"]}>
          <button
            onClick={() => {
              try {
                setResult(propagate(equation));
                setError("");
              } catch (err) {
                setError(err);
              }
            }}
          >
            Propagate!
          </button>
        </div>
        {error && <div className={styles["error"]}>{error.message}</div>}
        <h2>Result</h2>

        <div className={styles["formula"]}>
          {result && (
            <div className={styles["rendered"]}>{"$$ " + result + " $$"}</div>
          )}
        </div>

        <code>{result}</code>
        <div className={styles["group"]}>
          <button
            className={styles["small-button"]}
            onClick={() => {
              (window as any).MathJax.typeset();
            }}
          >
            Force typeset
          </button>
          <button
            className={styles["small-button"]}
            onClick={() => {
              (window as any).MathJax.typeset();
              setCopied(true);
              copy(result);
            }}
          >
            {copied ? "Copied!" : "Copy to Clipboard"}
          </button>
        </div>
        <h2>Examples</h2>
        <input type="text" disabled value="R_1 + R_2" />
        <input type="text" disabled value="R_1 + 1/(1/R_2 + 1/R_3)" />
        <input type="text" disabled value="P * V" />
        <input type="text" disabled value="x^2 + y^2 + z^2" />
      </main>
      <footer className={styles["footer"]}>Made with ❤️</footer>
    </div>
  );
};

export default Home;
